logging:
    level:
        come:
            example:
                spidercommunity: debug
        root: info
        web: trace
mybatis:
    mapper-locations: mapper/**/*.xml
pagehelper:
    helperDialect: mysql
    params: count=countSql
    reasonable: true
    supportMethodsArguments: true
server:
    port: 8080
spider:
    token:
        claim-userid-name: UserID
        expired-time: 1000*60*20
        header-name: Token
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/spider-community?serverTimezone=Asia/Shanghai
        username: root
    jackson:
        time-zone: GMT+8
